### ISSUE TITLE
CentOS 8 Build Error

### ISSUE THREAD

**Issue by jonakoudijs** [steamcmd/docker#36]
The automated CentOS 8 image build has started to fail consistently with the following error:
```
Error: Transaction check error:
  file /usr/share/gcc-8/python/libstdcxx/v6/__pycache__/xmethods.cpython-36.opt-1.pyc from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64
  file /usr/share/gcc-8/python/libstdcxx/v6/__pycache__/xmethods.cpython-36.pyc from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64
  file /usr/share/gcc-8/python/libstdcxx/v6/xmethods.py from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64

The command '/bin/sh -c yum -y install glibc.i686 libstdc++.i686  && yum -y clean all' returned a non-zero code: 1
```
It started yesterday in [this run](https://github.com/steamcmd/docker/actions/runs/136178044).

**Comment by jonakoudijs** [comment]
CentOS released a new version yesterday (8.2): https://wiki.centos.org/action/show/Manuals/ReleaseNotes/CentOS8.2004?action=show&redirect=Manuals%2FReleaseNotes%2FCentOSLinux8. Although the [CentOS Docker Hub](https://hub.docker.com/_/centos?tab=tags) shows no 8.2 tag or updated 8 tag (from yesterday) it could be related with the update and perhaps changes to the repository.

**Comment by jonakoudijs** [comment]
Reading a bit further, this bug report seems to be related: https://bugs.centos.org/view.php?id=16947. The release page also references this bug repot in the *Known Issues* section.

**Comment by jonakoudijs** [comment]
The problem is the installation of the `libstdc++.i686` package:
```
[root@25b8edfc5ea8 /]# yum install libstdc++.i686
...

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/share/gcc-8/python/libstdcxx/v6/__pycache__/xmethods.cpython-36.opt-1.pyc from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64
  file /usr/share/gcc-8/python/libstdcxx/v6/__pycache__/xmethods.cpython-36.pyc from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64
  file /usr/share/gcc-8/python/libstdcxx/v6/xmethods.py from install of libstdc++-8.3.1-5.el8.0.2.i686 conflicts with file from package libstdc++-8.3.1-4.5.el8.x86_64
```
The installation of the `glibc.i686` package works fine:
```
[root@25b8edfc5ea8 /]# yum  -y install glibc.i686
...

Installed:
  glibc-2.28-101.el8.i686                                                glibc-langpack-en-2.28-101.el8.x86_64

Complete!
```

**Comment by MindOnFire93** [comment]
Thanks dude, you really help me with this magic cmd: "yum install glibc.i686 libstdc++.i686 -y" and save me some time, I WAS AROUND THE WEB LIKE 40 MIN, AND NOTHING!! THANK you really <3

**Comment by jonakoudijs** [comment]
Haha you're welcome!
