### ISSUE TITLE
Add information for saving Steam in Docker volume

### ISSUE THREAD

**Issue by vigenere23** [steamcmd/docker#48]
In order to prevent update rechecking and Steam Guards, it is possible to attach the containers `/root/.steam` (on `alpine` version) folder to a host volume. It can be done, for example, using the volume command `-v steam:/root/.steam:z` like this:

```shell
# For the alpine version
docker run -it --rm -v steam:/root/.steam:z steamcmd/steamcmd:latest +login <username> <password>
```

I think such information should be added in the README since it's a very usefull technique to help going towards a CI approach with steamcmd.

Unfortunately, here are some concerns with this approach:

- A single Steam Guard will always be asked the first time the container is launched
- Maybe the volume could overwrite the steamcmd updates. We need to check if the `steamcmd` folder is a subfolder of the steam one or not (`/root/.steam` on `alpine` version).

**Comment by jonakoudijs** [comment]
That sounds interesting to add to the README. Are you currently using Steam on the host machine and as well and want to re-use the .steam directory from the host machine or do you intend to generate the `.steam` data once with a Docker container and re-use it for other containers?

I think the latter would be the most "Docker" way and something we could add to the README.

**Comment by vigenere23** [comment]
I intend to use the `.steam` folder of the container since the host may not have Steam installed. 

If a true CI machine is to be used, I guess the solution to prevent the first prompt needed to recognize the machine would be to either export the volume and reimport it on the machine or to use an account with Steam Guard disabled. But that's more of a problem with Steam directly since they don't offer one-time passwords :confused:.
