### ISSUE TITLE
Can't install dota on ubuntu

### ISSUE THREAD

**Issue by kheuton** [steamcmd/docker#61]
I've tried both the latest (ubuntu-20) as well as the ubuntu-18 image, and attempting to install dota fails with a cryptic error.

I use the following command:
`sudo docker run -it steamcmd/steamcmd:latest +login [my user]  [mypw] +app_update 570 +quit`

The game downloads and verifies the download, before showing the following:
```
 Update state (0x101) committing, progress: 8.62 (3868444206 / 44888062441)
 Update state (0x101) committing, progress: 15.71 (7053480492 / 44888062441)
src/clientdll/compatmanager.cpp (1988) : BFileExists( strSteam2WrapperSrcPath.String() )
assert_20221016233508_217.dmp[238]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221016233508_217.dmp

assert_20221016233508_217.dmp[238]: Finished uploading minidump (out-of-process): success = no

assert_20221016233508_217.dmp[238]: error: libcurl.so: cannot open shared object file: No such file or directory

assert_20221016233508_217.dmp[238]: file ''/tmp/dumps/assert_20221016233508_217.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

Error! App '570' state is 0x10C after update job.
Updating Workshop items for App '570'.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 29.80 (19715096 / 66151330)
Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
```

The key line seems to be `src/clientdll/compatmanager.cpp (1988) : BFileExists( strSteam2WrapperSrcPath.String() )`, and the things about libcurl.so are a red herring about uploading the minidump without a 32-bit curl library.

Installing other games (cs:go) works fine. Any idea where to start looking?

**Comment by jonakoudijs** [comment]
Apologies for missing this issue. Personally I have not encountered this problem before but I did have seen issues with installing/downloading/updating workshop items although I sadly do not know why. Did you found a solution for your problem?

**Comment by kheuton** [comment]
I haven't found any solution yet. I've tried both accounts that have many workshop items and new accounts without workshop items and I've been unsuccessful. Any idea of things that I could try?  I'm trying to do this as part of a continuous deployment system so some command-line interface is needed, I haven't tried just using the steam app.

**Comment by jonakoudijs** [comment]
Have you tried running the `steamcmd` command on a Linux machine like Ubuntu 20.04 without using Docker entirely? Then we could rule out any missing libraries/dependencies in the Docker image.

**Comment by kheuton** [comment]
I don't recall (but I think I have), and I don't have root access to a machine like that right now. I'll give it a shot when I'm home from the holidays

**Comment by xywf221** [comment]
just now I have the same problem，this problem occurs when I try all the latest images. finally I solved this problem with an old centos-7 tag

**Comment by jonakoudijs** [comment]
Sadly, I have not been able to reproduce the issue but I also don't have much spare time to further investigate. Please post any progress or more information on the problem in this issue. Perhaps we can find the culprit. For now I'll leave the issue open.

**Comment by xywf221** [comment]
> Sadly, I have not been able to reproduce the issue but I also don't have much spare time to further investigate. Please post any progress or more information on the problem in this issue. Perhaps we can find the culprit. For now I'll leave the issue open.

What can I offer to help you

**Comment by jonakoudijs** [comment]
Well it could help to test it with a minimal Ubuntu VM and see if it works then. And also it is very interesting to see why the old CentOS image tag works and the Ubuntu one doesn't. Perhaps we can find the difference in libraries or packages or something.

**Comment by kheuton** [comment]
I finally got around to testing it on an Ubuntu Machine (20.04 running on Windows Subsystem for Linux) and got the same error,  as when running with docker.

``` Update state (0x81) verifying update, progress: 99.43 (48853443620 / 49133282762)
Error! App '570' state is 0x10C after update job.
Updating Workshop items for App '570'.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 2.27 (7340032 / 323659339)
 Update state (0x61) downloading, progress: 77.02 (249287883 / 323659339)
Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
```

**Comment by jonakoudijs** [comment]
Very interesting, that would suggest that Ubuntu might be missing a required package or using a different base lib (version). Especially since an old CentOS tag seems to be working.

**Comment by kheuton** [comment]
I found a different steam-game adjacent project experiencing the same issue: https://github.com/truckersmp-cli/truckersmp-cli/pull/159 They seem to be able to make sense of it and move on. Is there something in that issue that adds insight here? I suppose I can always ask them
