### ISSUE TITLE
How to run with windows

### ISSUE THREAD

**Issue by JensvandeWiel** [steamcmd/docker#63]
Hello, i want to run the eqivalent of this on windows:
docker run -it -v $PWD:/data steamcmd/steamcmd:latest +login anonymous +force_install_dir /data +app_update 740 +quit
how should i do that?

**Comment by jonakoudijs** [comment]
Running the Windows containers is a bit finicky. It depends on the Windows version used and it might not always work so it is a bit of a trial and error. As you can see in the README of this project there are several Windows tags:

* [windows-1909](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-1909/Dockerfile) (unavailable)
* [windows-1903](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-1903/Dockerfile) (unavailable)
* [windows-1809, windows](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-1809/Dockerfile)
* [windows-core-2019, windows-core](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-core-2019/Dockerfile)
* [windows-core-1909](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-core-1909/Dockerfile) (unavailable)
* [windows-core-1903](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-core-1903/Dockerfile) (unavailable)
* [windows-core-1809](https://github.com/steamcmd/docker/blob/master/dockerfiles/windows-core-1809/Dockerfile)

The ones that contain _(unavailable)_ are not (yet) build and you would have to build them yourself. The other tags can be used like normal. For example, the main `windows` tag:
```
docker run -it steamcmd/steamcmd:windows
```
Or a more specific tag:
```
docker run -it steamcmd/steamcmd:windows-core-1809
```

**Comment by JensvandeWiel** [comment]
thanks, but i get a error that the volume syntax is not correct

**Comment by JensvandeWiel** [comment]
I used this:
`docker run -it -v ${PWD.Path}:/data steamcmd/steamcmd:windows-core-2019 +login anonymous +force_install_dir /data +app_update 740 +quit`

Error:
`docker: Error response from daemon: Unrecognised volume spec: invalid volume specification: ':/data'.`

**Comment by jonakoudijs** [comment]
This seems to be a problem with the Docker command and not necessarily the steamcmd image. Please try it without mounting the volume (`-v ${PWD.Path}:/data`) and then with the other options.

**Comment by JensvandeWiel** [comment]
without it it works fine

**Comment by JensvandeWiel** [comment]
This command worked for me:  `docker run -it -v C:\csgo:C:\data steamcmd/steamcmd:windows-core-2019  +force_install_dir C:\data +login anonymous +app_update 740 +quit` make sure that the source folder exists on your pc
