### ISSUE TITLE
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by henaff** [steamcmd/docker#67]
#### Problem:
When running the Docker container for `steamcmd/steamcmd:latest`, I'm encountering an issue related to a missing shared object file `steamservice.so`.

#### Steps to Reproduce:
1. Pulled the `steamcmd/steamcmd:latest` image: `docker pull steamcmd/steamcmd:latest`
2. Ran the container with entrypoint as `/bin/sh`: `docker run --entrypoint /bin/sh -it steamcmd/steamcmd:latest`
3. Executed `steamcmd`.

#### Expected Behavior:
I expect `steamcmd` to launch successfully without any errors.

#### Actual Behavior:
Received the following error message:
```
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
```

#### Environment:
- OS: Ubuntu 20
- Docker version: 24.0.6
- Image: `steamcmd/steamcmd:latest`

#### Logs:

```
# steamcmd
ln: failed to create symbolic link '/root/.steam/root': No such file or directory
ln: failed to create symbolic link '/root/.steam/steam': No such file or directory
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Steam>
```

### Additional Context:

/root/Steam/logs/stderr.txt is empty

**Comment by henaff** [comment]
I found a valve precision about this issue. It's not from your docker files sorry.

**Comment by jonakoudijs** [comment]
No worries. You are not the first person reporting this. Especially when experiencing different problems this error can be confusing.

For future reference; where did you find the Valve issue?

**Comment by jonakoudijs** [comment]
Thanks for the info. I am re-opening this issue because even though it does not directly seem to be causing issues, it would be nice to include this in the Docker builds as well.

**Comment by jonakoudijs** [comment]
This fix has now been included in all the linux images. See commit: https://github.com/steamcmd/docker/commit/7f8456a3ce53264ed42cf93d24090811c98909bc.
