### ISSUE TITLE
`/root/.local/share/Steam/steamcmd/steamcmd.sh: line 39:    10 Segmentation fault      $DEBUGGER "$STEAMEXE" "$@"`

### ISSUE THREAD

**Issue by devioa** [steamcmd/docker#69]
![image](https://github.com/steamcmd/docker/assets/38558065/b8c0081f-d116-4ae4-8658-211303eb8c81)

**Comment by jonakoudijs** [comment]
I see `OpenWrt` as an hostname. Do you use an arm-based system by any chance? SteamCMD is not compatible with ARM and probably causes the segmentation fault.

**Comment by devioa** [comment]
I now know the reason. Steam cmd only has 32-bit executable binary files, while OpenWrt only supports 64 bit programs, so it cannot run.
